config/routes.rb
IrinasSalon::Application.routes.draw do
  devise_for :users
  resources :appointments
 

  root "appointments#index"

  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :user
	
	before_validation :set_end_date
	validate :appointment_overlap
	validate :early_appointment
	validate :late_appointment
	validate :more_than_one_appointment_per_two_weeks
	validate :time_selected

	after_create :update_all_connected_clients_add_event
	after_destroy :update_all_connected_clients_remove_event


	def time_selected 
		if self.start_time == self.start_time.at_beginning_of_day
			errors.add(:start_time, "Please select appointment time from the drop down menu.")
		end

	end
	def more_than_one_appointment_per_two_weeks

		unless self.user.is_admin
			apt_time = self.start_time
			#debugger
			if Appointment.where("((start_time < ? AND start_time > ?) OR (start_time > ? AND start_time < ?)) AND user_id = ?", apt_time, (apt_time - 14.days), apt_time, (apt_time + 14.days), self.user.id).first
				errors.add(:start_time, "System only allows one appointment per two weeks. Please call directly to make an appointment.")


			end


		end

	end


	def early_appointment 
		if self.start_time  < (DateTime.now + 1.days).beginning_of_day && !self.user.is_admin
			errors.add(:start_time, "To make an appointment within the next 24 hours please call us directly.")
		end
	end

	def late_appointment 
		if self.start_time  > (DateTime.now + 90.days) && !self.user.is_admin
			errors.add(:start_time, "You can only make an appointment 90 days ahead.")
		end
	end

	def  update_all_connected_clients_remove_event
    Pusher['appointments'].trigger('remove_event', {
      id: self.id
    })
	end
	def  update_all_connected_clients_add_event
    Pusher['appointments'].trigger('add_event', {
      id: self.id
    })
	end

  def appointment_overlap

  	exists = Appointment.where("start_time < ? AND end_time > ? AND id != ?", self.end_time, self.start_time, self.id.nil? ? -1 : self.id)
  	#debugger
    unless exists.blank?
      errors.add(:start_time, "This time is in use. Please select another time slot.")
    end
  end


	def set_end_date

		if self.appointment_type
			#debugger
			duration_type = [60, 90, 120]

			duration = duration_type[self.appointment_type.to_i]

			self.end_time = self.start_time.advance(minutes: duration)
		end
	end


end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :appointments

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?





  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :phone_number
    devise_parameter_sanitizer.for(:sign_up) << :full_name

    devise_parameter_sanitizer.for(:account_update) << :phone_number
    devise_parameter_sanitizer.for(:account_update) << :full_name

  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /appointments
  # GET /appointments.json
  def index
    gon.admin = current_user.is_admin


    #@appointments_events = @appointments.to_json(current_user.id.to_s).html_safe
    respond_to do |format|
      format.html {
        @appointment = Appointment.new
      }

      

      format.json { 
        #debugger
        if params[:id]
          @appointment = Appointment.find(params[:id])
        else
          @appointments = Appointment.where("start_time >= ? AND start_time <= ?", DateTime.strptime(params[:start],'%s'), DateTime.strptime(params[:end],'%s'))
        end
        
      
        format.json { render json: @appointments }
      }
    end
  end


  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/newr
  def new
    @appointment = Appointment.new

  end

  # GET /appointments/1/edit
  def edit


  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.user = current_user

    #debugger
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.js
      else
        format.html { render action: 'new' }
        format.js
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    #debugger
    respond_to do |format|


      if (params[:appointment_form_action] == "commit")
        @appointment.update(appointment_params)
      elsif (params[:appointment_form_action] == "cancel")
        @appointment.destroy
      elsif (params[:unblock_appointment])
        @appointment.destroy
      end
      

      format.js
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:start_time, :end_time, :appointment_type, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<% edit_json = (params[:format] == "js" &&  params[:action] == "edit") %>

<%= form_for @appointment do |f| %>
  <%= hidden_field_tag :appointment_form_action %>
  <div class="make_appointment_server_info alert alert-error"></div>
  <h2> Appointment Information </h2>

  <% if edit_json %>
    <p>Name: <%= @appointment.user.full_name %></p>
    <p>Phone number: <%= @appointment.user.phone_number %></p>
    <p>Day: <%= @appointment.start_time.strftime("%A - %B %d") %></p>
    <p>Starts: <%= @appointment.start_time.strftime("%I:%M %p") %></p>
    <p>Ends: <%= @appointment.end_time.strftime("%I:%M %p") %></p>

  <% else %>

    <div class="field">
      <h4> Select Type </h2>
      <%= f.select :appointment_type, [['Regular (60 minutes)', 0], ['Long (90  minutes)', 1], ['Longer (120 minutes)', 2]] %>
    </div>


    <div class="field">
      <%= f.hidden_field :start_time, id: 'timepicker' %> 
      <div id="appointment_date_text">
      On <span style="font-weight:bold;" id="full_date"></span> at 
      </div> 
<!--       <div class="bootstrap-timepicker">
        <%#= f.text_field :start_time, id: 'timepicker', class:'input-small' %> 
      </div> -->
      <div>
        <%= select_tag :appointment_time, id:'appointment_time' %>
      </div>
    </div>



  <% end %>


  <div class="field">
     <h2> Comments (optional) </h2>
    <%= f.text_area :comment, style: ' height:50px;' %> 
  </div>


  <div class="actions">
    <%= f.submit nil, class: 'btn btn-success' %>
    <%= f.submit "Cancel Appointment", name: 'cancel', class: 'btn btn-danger' if edit_json %>
  </div>
<% end %>

app/views/appointments/_form_admin.html.erb
<%= form_for @appointment do |f| %>
  <%= hidden_field_tag :block_appointments %>
  <div class="make_appointment_server_info alert alert-error"></div>

  <h4> Date and Time </h2>

  <div class="field">
    
    <div>
      Day: <span style="font-weight:bold;" id="block_full_date"></span>  
    </div> 

    
    <div class="bootstrap-timepicker">
      Start time: <%= f.text_field :start_time, id: 'timepicker_start', class:'input-small' %> 
    </div>

    
    <div class="bootstrap-timepicker">
      End time: <%= f.text_field :end_time, id: 'timepicker_end', class:'input-small' %> 
    </div>

    
    <div>
      Comments:
      <%= f.text_area :comment, class:'input-small', style:'width:360px; height: 90px;' %> 
    </div>

  </div>
  <div class="actions">
    <%= f.submit "Block", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/appointments/_form_admin_unblock.html.erb
<%= form_for @appointment do |f| %>
  <%= hidden_field_tag :unblock_appointment %>
  <div class="make_appointment_server_info alert alert-error"></div>

  <h4> Date and Time </h2>

  <div class="field">
    
    <p>
      Day: <%= @appointment.start_time.strftime("%A - %B %d") %>
    </p> 
    <p>
    Start time: <%= @appointment.start_time.strftime("%T") %>
    </p>
    <p>
    End time: <%= @appointment.end_time.strftime("%T") %>
    </p>
    <p>
    Comment: <%= @appointment.comment %>
    </p>

  </div>
  <div class="actions">
    <%= f.submit "Unblock", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/appointments/create.js.erb
<% if @appointment.errors.count > 0 %>
	$(".make_appointment_server_info").html("<%= @appointment.errors.messages[@appointment.errors.messages.first.first][0] %>");
	$(".make_appointment_server_info").show();
<% else %>
	$('#make_appointment').modal('hide');
	$("#calendar").fullCalendar( 'unselect' )
<% end %>

app/views/appointments/edit.html.erb
<% if params[:type] == "blocked_event" && current_user.is_admin %>
	<%= render 'form_admin_unblock' %>
<% else %>

	<%= render 'form' %>

<% end %>

app/views/appointments/index.html.erb
<%= image_tag 'preload_img.gif', id: 'loading' %>
<div id='calendar'></div>


<div id="make_appointment" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Make an appointment</h3>
  </div>
  <div class="modal-body">
    <div id="regular">
      <%= render 'form' %>
    </div>
    <div id="appointment_blocker" style="display:none;">
      <%= render 'form_admin' if current_user.is_admin %>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Go back</button>
  </div>
</div>


<div id="edit_appointment" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Edit an appointment</h3>
  </div>
  <div class="modal-body">
    <div id="edit_appointment_form">
      
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>


<div id="info_popup" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Information</h3>
  </div>
  <div class="modal-body">
    <p></p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Length:</strong>
  <%= @appointment.length %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/update.js.erb
<% if params[:appointment_form_action] == "commit" %>
	$('#edit_appointment').modal('hide');
	show_alert("Appointment Update", "Your appointment was succesfully updated.");

<% elsif params[:appointment_form_action] == "cancel" %>

	
	$('#edit_appointment').modal('hide');

	show_alert("Appointment Update", "Your appointment was cancelled. Thank you!");

<% elsif params[:unblock_appointment] %>
	$('#edit_appointment').modal('hide');

	show_alert("Appointment Update", "Succesfully unblocked!");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Irina's Salon</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="http://js.pusher.com/2.1/pusher.min.js" type="text/javascript"></script>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Quicksand:400,700,300' rel='stylesheet' type='text/css'>


<!--[if lt IE 9]>
  <script src="js/html5shiv.js"></script>
    <script src="js/respond.src.js"></script>
<![endif]-->


</head>
<body>
    <div id="info_box">
    Click to start making an appointment
    </div>


    <div id="wrapper">
        <div id="container">
            <header>
                <div class="container_24">
                    <h1 id="logo">
                        <a href="#home"><%= image_tag "logo.png" %></a>
                    </h1>
                    <!-- <a href="#" class="donate">Donate Now!</a> -->

                        <div id="user_nav">
                          <% if user_signed_in? %>
                            <strong>Hello <%= current_user.full_name %></strong>
                            (<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>  |
                            <%= link_to "Edit Profile", edit_user_registration_path %>)
                            
                          <% else %>
                            <%= link_to "Sign up", new_user_registration_path %> or
                            <%= link_to "Sign in", new_user_session_path %>
                          <% end %>
                        </div>

                </div>

            </header>
            <section id="content">
                <div class="inner">
                  <div class="container_24">
                        <nav id="menu">
                            <ul class="mainmenu">
                                <li><a href="#home">N / A</a></li>
                                <li><a href="#about">N / A</a></li>
                                <li>
                                    <a href="javascript:void(0);">N / A</a>
                                    <ul class="sub_menu level1">
                                        <li><a href="#media-images">N / A</a></li>
                                        <li><a href="#media-videos">N / A</a></li>
                                    </ul>
                                </li>
                                <li><a href="#events">N / A</a></li>
                                <li class="act"><a href="#scheduler">Book</a></li>
                                <li><a href="#contacts">N / A</a></li>
                                <div class="clear"></div>
                            </ul>
                        </nav>

                    </div>

                  <div class="wrap container_24">
                      <div class="ajaxed_content" style="height: 505px; overflow:auto; padding:15px">
                        <%= yield %>
                      </div>
                    </div>
                    <div class="container_24">
                      <%= image_tag "shadow.png" %>
                    </div>
                </div>
            </section>
            <footer>
                <div class="container_24">
                  <div class="clearfix">
                      <div class="fleft">&copy; Copyright 2020 <h4>SJW Works</h4> All Rights Reserved.</div>
                        <div class="fright">
                          <!-- player -->
    <!--                         <div id="jquery_jplayer" class="jp-jplayer">
                                
                            </div>
                            <div id="jp_container" class="jp-audio">
                                <ul class="jp-controls">
                                    <li>
                                      <a class="jp-mute" title="mute" tabindex="1" href="javascript:;" style="display: none;"></a>
                                    </li>
                                    <li>
                                      <a class="jp-unmute" title="unmute" tabindex="1" href="javascript:;" style="display: inline;"></a>
                                    </li>
                                    <li>
                                      <a class="jp-volume-max" title="max volume" tabindex="1" href="javascript:;"></a>
                                    </li>
                                </ul>
                                <div class="jp-txt">Sound:</div>
                                <div class="jp-volume-bar">
                                    <div class="jp-volume-bar-value" style="width: 0%;"></div>
                                </div>
                            </div> -->
                            <!-- /player -->
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>    
</body>
</html>